info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        name: HariTech
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
server:
    error:
        include-binding: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassname: org.h2.Driver
        password: Hari@123
        url: jdbc:h2:mem:testdb-dev-environment
        username: sarkiharish42
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
